mod decl;
mod doc;
mod doc_type;
mod file;
mod flow;
mod module;
mod module_returns;
mod owner_binding;
mod property;
mod signature;
mod support;
mod table_shape;
mod use_site;

pub(crate) use decl::{SummaryDeclAnalysis, analyze_decl_summary};
pub use doc::analyze_doc_summary;
pub use doc_type::analyze_doc_type_summary;
pub use file::analyze_file_summary;
pub use flow::analyze_flow_summary;
pub use module_returns::{analyze_module_return_points, analyze_signature_return_points};
pub use owner_binding::analyze_doc_owner_binding_summary;
pub use property::analyze_property_summary;
pub use signature::analyze_signature_summary;
pub(crate) use table_shape::analyze_table_expr_shape;
pub use table_shape::analyze_table_shape_summary;
pub use use_site::analyze_use_site_summary;
